//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Account"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub r#type: String,
    pub provider: String,
    pub provider_account_id: String,
    pub refresh_token: Option<String>,
    pub access_token: Option<String>,
    pub expires_at: Option<i32>,
    pub refresh_token_expires_in: Option<i32>,
    pub token_type: Option<String>,
    pub scope: Option<String>,
    pub id_token: Option<String>,
    pub session_state: Option<String>,
    pub created_at: Option<i32>,
    pub secret_valid_until: Option<i32>,
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Type,
    Provider,
    #[sea_orm(column_name = "providerAccountId")]
    ProviderAccountId,
    RefreshToken,
    AccessToken,
    ExpiresAt,
    RefreshTokenExpiresIn,
    TokenType,
    Scope,
    IdToken,
    SessionState,
    CreatedAt,
    SecretValidUntil,
    #[sea_orm(column_name = "userId")]
    UserId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    User,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Text.def(),
            Self::Type => ColumnType::Text.def(),
            Self::Provider => ColumnType::Text.def(),
            Self::ProviderAccountId => ColumnType::Text.def(),
            Self::RefreshToken => ColumnType::Text.def().null(),
            Self::AccessToken => ColumnType::Text.def().null(),
            Self::ExpiresAt => ColumnType::Integer.def().null(),
            Self::RefreshTokenExpiresIn => ColumnType::Integer.def().null(),
            Self::TokenType => ColumnType::Text.def().null(),
            Self::Scope => ColumnType::Text.def().null(),
            Self::IdToken => ColumnType::Text.def().null(),
            Self::SessionState => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::Integer.def().null(),
            Self::SecretValidUntil => ColumnType::Integer.def().null(),
            Self::UserId => ColumnType::Text.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::User => Entity::belongs_to(super::user::Entity)
                .from(Column::UserId)
                .to(super::user::Column::Id)
                .into(),
        }
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
