//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude ;

pub mod account ;
pub mod contact ;
pub mod conversation ;
pub mod feedback ;
pub mod friend ;
pub mod game ;
pub mod message ;
pub mod r#move ;
pub mod notification ;
pub mod participant ;
pub mod session ;
pub mod user ;
pub mod user_settings ;
pub mod user_stats ;
pub mod verification_token ;