//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Notification"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub user_id: String,
    pub sender_id: String,
    pub r#type: String,
    pub msg: Option<String>,
    pub conversation_id: Option<String>,
    pub game_id: Option<String>,
    pub read: bool,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    #[sea_orm(column_name = "userId")]
    UserId,
    #[sea_orm(column_name = "senderId")]
    SenderId,
    Type,
    Msg,
    #[sea_orm(column_name = "conversationId")]
    ConversationId,
    #[sea_orm(column_name = "gameId")]
    GameId,
    Read,
    #[sea_orm(column_name = "createdAt")]
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    User,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Text.def(),
            Self::UserId => ColumnType::Text.def(),
            Self::SenderId => ColumnType::Text.def(),
            Self::Type => ColumnType::Text.def(),
            Self::Msg => ColumnType::Text.def().null(),
            Self::ConversationId => ColumnType::Text.def().null(),
            Self::GameId => ColumnType::Text.def().null(),
            Self::Read => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::User => Entity::belongs_to(super::user::Entity)
                .from(Column::UserId)
                .to(super::user::Column::Id)
                .into(),
        }
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
