//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Session"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub session_token: String,
    pub user_id: String,
    pub expires: DateTime,
    pub device_info: Option<String>,
    pub ip_address: Option<String>,
    pub last_active: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    #[sea_orm(column_name = "sessionToken")]
    SessionToken,
    #[sea_orm(column_name = "userId")]
    UserId,
    Expires,
    #[sea_orm(column_name = "deviceInfo")]
    DeviceInfo,
    #[sea_orm(column_name = "ipAddress")]
    IpAddress,
    #[sea_orm(column_name = "lastActive")]
    LastActive,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    User,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Text.def(),
            Self::SessionToken => ColumnType::Text.def().unique(),
            Self::UserId => ColumnType::Text.def(),
            Self::Expires => ColumnType::DateTime.def(),
            Self::DeviceInfo => ColumnType::Text.def().null(),
            Self::IpAddress => ColumnType::Text.def().null(),
            Self::LastActive => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::User => Entity::belongs_to(super::user::Entity)
                .from(Column::UserId)
                .to(super::user::Column::Id)
                .into(),
        }
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
