//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "UserSettings"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub two_factor_enabled: bool,
    pub two_factor_secret: Option<String>,
    pub is_public_profile: bool,
    pub show_stats: bool,
    pub show_match_history: bool,
    pub show_online_status: bool,
    pub game_invite_policy: String,
    pub notify_new_games: bool,
    pub notify_messages: bool,
    pub notify_friend_requests: bool,
    pub push_notifications_enabled: bool,
    pub newsletter_enabled: bool,
    pub is_anonymized: bool,
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    #[sea_orm(column_name = "twoFactorEnabled")]
    TwoFactorEnabled,
    #[sea_orm(column_name = "twoFactorSecret")]
    TwoFactorSecret,
    #[sea_orm(column_name = "isPublicProfile")]
    IsPublicProfile,
    #[sea_orm(column_name = "showStats")]
    ShowStats,
    #[sea_orm(column_name = "showMatchHistory")]
    ShowMatchHistory,
    #[sea_orm(column_name = "showOnlineStatus")]
    ShowOnlineStatus,
    #[sea_orm(column_name = "gameInvitePolicy")]
    GameInvitePolicy,
    #[sea_orm(column_name = "notifyNewGames")]
    NotifyNewGames,
    #[sea_orm(column_name = "notifyMessages")]
    NotifyMessages,
    #[sea_orm(column_name = "notifyFriendRequests")]
    NotifyFriendRequests,
    #[sea_orm(column_name = "pushNotificationsEnabled")]
    PushNotificationsEnabled,
    #[sea_orm(column_name = "newsletterEnabled")]
    NewsletterEnabled,
    #[sea_orm(column_name = "isAnonymized")]
    IsAnonymized,
    #[sea_orm(column_name = "userId")]
    UserId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    User,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Text.def(),
            Self::TwoFactorEnabled => ColumnType::Boolean.def(),
            Self::TwoFactorSecret => ColumnType::Text.def().null(),
            Self::IsPublicProfile => ColumnType::Boolean.def(),
            Self::ShowStats => ColumnType::Boolean.def(),
            Self::ShowMatchHistory => ColumnType::Boolean.def(),
            Self::ShowOnlineStatus => ColumnType::Boolean.def(),
            Self::GameInvitePolicy => ColumnType::Text.def(),
            Self::NotifyNewGames => ColumnType::Boolean.def(),
            Self::NotifyMessages => ColumnType::Boolean.def(),
            Self::NotifyFriendRequests => ColumnType::Boolean.def(),
            Self::PushNotificationsEnabled => ColumnType::Boolean.def(),
            Self::NewsletterEnabled => ColumnType::Boolean.def(),
            Self::IsAnonymized => ColumnType::Boolean.def(),
            Self::UserId => ColumnType::Text.def().unique(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::User => Entity::belongs_to(super::user::Entity)
                .from(Column::UserId)
                .to(super::user::Column::Id)
                .into(),
        }
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
