//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "User"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: Option<String>,
    pub nickname: Option<String>,
    pub email: String,
    pub password: Option<String>,
    pub email_verified: Option<DateTime>,
    pub image: Option<String>,
    pub bio: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Nickname,
    Email,
    Password,
    #[sea_orm(column_name = "emailVerified")]
    EmailVerified,
    Image,
    Bio,
    #[sea_orm(column_name = "createdAt")]
    CreatedAt,
    #[sea_orm(column_name = "updatedAt")]
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Account,
    Friend,
    Game,
    Message,
    Notification,
    Participant,
    Session,
    UserSettings,
    UserStats,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Text.def(),
            Self::Name => ColumnType::Text.def().null(),
            Self::Nickname => ColumnType::Text.def().null().unique(),
            Self::Email => ColumnType::Text.def().unique(),
            Self::Password => ColumnType::Text.def().null(),
            Self::EmailVerified => ColumnType::DateTime.def().null(),
            Self::Image => ColumnType::Text.def().null(),
            Self::Bio => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Account => Entity::has_many(super::account::Entity).into(),
            Self::Friend => Entity::has_many(super::friend::Entity).into(),
            Self::Game => Entity::has_many(super::game::Entity).into(),
            Self::Message => Entity::has_many(super::message::Entity).into(),
            Self::Notification => Entity::has_many(super::notification::Entity).into(),
            Self::Participant => Entity::has_many(super::participant::Entity).into(),
            Self::Session => Entity::has_many(super::session::Entity).into(),
            Self::UserSettings => Entity::has_one(super::user_settings::Entity).into(),
            Self::UserStats => Entity::has_one(super::user_stats::Entity).into(),
        }
    }
}

impl Related<super::account::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Account.def()
    }
}

impl Related<super::friend::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Friend.def()
    }
}

impl Related<super::game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Game.def()
    }
}

impl Related<super::message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Message.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::participant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participant.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::user_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSettings.def()
    }
}

impl Related<super::user_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
